/* DSblock model generated by Dymola from Modelica model space.TbLib.Test1
 Dymola Version 2015 FD01 (32-bit), 2014-11-04 translated this at Sat Apr 09 15:35:43 2016

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

BreakSectionFunctionDef(1)
BreakSectionFunctionDef(0)
BreakSectionFunctionDef(2)
BreakSectionFunctionDef(3)
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="space.TbLib.Test1";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/bapty/appdata/roaming/dynasim/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
W_[37] = 0;
W_[72] = 0;
W_[73] = 0;
W_[56] = 0;
W_[0] = 0;
W_[36] = 0;
W_[12] = 0;
W_[79] = 0;
W_[81] = 0;
W_[58] = 0;
W_[11] = 0;
W_[78] = 0.0;
W_[75] = 0.0;
W_[80] = 0.0;
W_[52] = 0.0;
W_[45] = 0.0;
W_[49] = 0.0;
W_[57] = 0.0;
W_[8] = 0.0;
W_[4] = 0.0;
W_[10] = 0.0;
BoundParameterSection
W_[14] = DP_[6];
W_[15] = W_[14]+DP_[7];
W_[16] = W_[15]+DP_[8];
W_[7] = 0.01*DP_[2]*DP_[1];
InitialSection
InitialSection
InitialStartSection
InitialStartSection2
W_[6] = DP_[4];
W_[17] = DP_[12];
W_[18] = DP_[10];
W_[19] = DP_[10];
InitialSection
DefaultSection
InitializeData(0)
InitialSection
Aux_[0] = W_[17];
Aux_[2] = W_[19];
Aux_[1] = W_[18];
Aux_[3] = W_[6];
InitialSection
Aux_[3] = DP_[4];
InitialSection2
W_[6] = Aux_[3];
InitialSection
Aux_[0] = DP_[12];
InitialSection2
W_[17] = Aux_[0];
InitialSection
Aux_[2] = DP_[10];
InitialSection2
W_[19] = Aux_[2];
InitialSection
Aux_[1] = DP_[10];
InitialSection2
W_[18] = Aux_[1];
InitialSection
Init=false;InitializeData(2);Init=true;
EndInitialSection

OutputSection

DynamicsSection
beginwhenBlock
helpvar[0] = sampleNew(DP_[4], DP_[2], 0);
whenModelicaS(helpvar[0])
  W_[6] = Time;
endwhenModelica()
endwhenBlock
W_[5] = DP_[3]+(IF LessTime(DP_[4], 0) OR GreaterEqualTime(W_[6]+W_[7], 1) THEN 0
   ELSE DP_[0]);
BreakSectionFunctionCallNew(0);
BreakSectionFunctionEnd()
BreakSectionFunctionStart(1);
beginwhenBlock
helpvar[1] = sampleNew(DP_[12], DP_[9], 1);
whenModelica(PRE(W_[19], 0) != 0 AND helpvar[1], 0) 
  W_[19] = PRE(W_[18], 1);
  W_[17] = Time;
endwhenModelica()
endwhenBlock

W_[13] = DP_[11]+(IF LessTime(DP_[12], 2) OR W_[19] == 0 OR GreaterEqualTime(
  W_[17]+W_[16], 3) THEN 0 ELSE IF LessTime(W_[17]+W_[14], 4) THEN divmacro((
  Time-W_[17])*DP_[5],"(time-samplesolarflux1.trapezoid1.T0)*samplesolarflux1.trapezoid1.amplitude",
  W_[14],"samplesolarflux1.trapezoid1.T_rising") ELSE IF LessTime(W_[17]+W_[15],
   5) THEN DP_[5] ELSE divmacro((W_[17]+W_[16]-Time)*DP_[5],"(samplesolarflux1.trapezoid1.T0+samplesolarflux1.trapezoid1.T_falling-time)*samplesolarflux1.trapezoid1.amplitude",
  W_[16]-W_[15],"samplesolarflux1.trapezoid1.T_falling-samplesolarflux1.trapezoid1.T_width"));
W_[21] = DP_[23]*W_[13];
W_[60] = DP_[45]*W_[13];
W_[40] = DP_[34]*W_[13];
BreakSectionFunctionEnd()
BreakSectionFunctionStart(2);
{ /* Non-linear system of equations to solve. */
  /* Nonlinear system of equations number = 1. */
/* Introducing 47 common subexpressions used in 35 expressions */
/* Of the common subexpressions 41 are reals, 0 are integers, and 6
   are booleans. */
const char*const varnames_[]={"solar_panels_32.diode1.v", "solar_panels_31.diode2.v",
   "solar_panels_31.diode1.v", "solar_panels_33.diode2.v", "solar_panels_33.diode1.v",
   "varload1.pin_p.i"};
const double nominal_[]={1, 1, 1, 1, 1, 1};
NonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 6, 0, 1, 0, 5);
NonLinearSystemSave(X_[0], 0);
NonLinearSystemSave(W_[60], 1);
NonLinearSystemSave(W_[40], 2);
NonLinearSystemSave(W_[21], 3);
NonLinearSystemSave(W_[5], 4);
SetInitVectorNH(x__, 1, W_[43], Remember_(W_[43], 0));
SetInitVectorNH(x__, 2, W_[67], Remember_(W_[67], 1));
SetInitVectorNH(x__, 3, W_[63], Remember_(W_[63], 2));
SetInitVectorNH(x__, 4, W_[31], Remember_(W_[31], 3));
SetInitVectorNH(x__, 5, W_[24], Remember_(W_[24], 4));
SetInitVectorNH(x__, 6, W_[3], Remember_(W_[3], 5));
Residues;
  helpvar[2] = divmacro(W_[43],"solar_panels_32.diode1.v",DP_[25],
    "solar_panels_32.diode1.Vt");
  helpvar[3] = GreaterS(helpvar[2],"solar_panels_32.diode1.v/solar_panels_32.diode1.Vt",
     DP_[26],"solar_panels_32.diode1.Maxexp", 0);
  W_[44] = IF helpvar[3] THEN DP_[24]*(exp(DP_[26])*(1.0+helpvar[2]-DP_[26])-1)+
    divmacro(W_[43],"solar_panels_32.diode1.v",DP_[27],"solar_panels_32.diode1.R")
     ELSE DP_[24]*(exp(helpvar[2])-1)+divmacro(W_[43],"solar_panels_32.diode1.v",
    DP_[27],"solar_panels_32.diode1.R");
  helpvar[4] = divmacro(W_[67],"solar_panels_31.diode2.v",DP_[40],
    "solar_panels_31.diode2.Vt");
  helpvar[5] = GreaterS(helpvar[4],"solar_panels_31.diode2.v/solar_panels_31.diode2.Vt",
     DP_[41],"solar_panels_31.diode2.Maxexp", 1);
  W_[68] = IF helpvar[5] THEN DP_[39]*(exp(DP_[41])*(1.0+helpvar[4]-DP_[41])-1)+
    divmacro(W_[67],"solar_panels_31.diode2.v",DP_[42],"solar_panels_31.diode2.R")
     ELSE DP_[39]*(exp(helpvar[4])-1)+divmacro(W_[67],"solar_panels_31.diode2.v",
    DP_[42],"solar_panels_31.diode2.R");
  helpvar[6] = divmacro(W_[63],"solar_panels_31.diode1.v",DP_[36],
    "solar_panels_31.diode1.Vt");
  helpvar[7] = GreaterS(helpvar[6],"solar_panels_31.diode1.v/solar_panels_31.diode1.Vt",
     DP_[37],"solar_panels_31.diode1.Maxexp", 2);
  W_[64] = IF helpvar[7] THEN DP_[35]*(exp(DP_[37])*(1.0+helpvar[6]-DP_[37])-1)+
    divmacro(W_[63],"solar_panels_31.diode1.v",DP_[38],"solar_panels_31.diode1.R")
     ELSE DP_[35]*(exp(helpvar[6])-1)+divmacro(W_[63],"solar_panels_31.diode1.v",
    DP_[38],"solar_panels_31.diode1.R");
  helpvar[8] = divmacro(W_[24],"solar_panels_33.diode1.v",DP_[14],
    "solar_panels_33.diode1.Vt");
  helpvar[9] = GreaterS(helpvar[8],"solar_panels_33.diode1.v/solar_panels_33.diode1.Vt",
     DP_[15],"solar_panels_33.diode1.Maxexp", 3);
  W_[25] = IF helpvar[9] THEN DP_[13]*(exp(DP_[15])*(1.0+helpvar[8]-DP_[15])-1)+
    divmacro(W_[24],"solar_panels_33.diode1.v",DP_[16],"solar_panels_33.diode1.R")
     ELSE DP_[13]*(exp(helpvar[8])-1)+divmacro(W_[24],"solar_panels_33.diode1.v",
    DP_[16],"solar_panels_33.diode1.R");
  W_[28] = W_[25]-W_[21];
  W_[76] = W_[28]+W_[3];
  W_[2] = W_[5]*W_[3];
  W_[77] = W_[2]-X_[0];
  W_[33] =  -DP_[21]*W_[28];
  W_[27] = W_[60]-W_[64];
  W_[71] = DP_[44]*W_[27];
  W_[69] = DP_[43]*W_[27];
  W_[55] = DP_[33]*W_[27];
  W_[53] = DP_[32]*W_[27];
  helpvar[10] = divmacro(W_[31],"solar_panels_33.diode2.v",DP_[18],
    "solar_panels_33.diode2.Vt");
  helpvar[11] = GreaterS(helpvar[10],"solar_panels_33.diode2.v/solar_panels_33.diode2.Vt",
     DP_[19],"solar_panels_33.diode2.Maxexp", 4);
  W_[32] = IF helpvar[11] THEN DP_[17]*(exp(DP_[19])*(1.0+helpvar[10]-DP_[19])-1)
    +divmacro(W_[31],"solar_panels_33.diode2.v",DP_[20],"solar_panels_33.diode2.R")
     ELSE DP_[17]*(exp(helpvar[10])-1)+divmacro(W_[31],"solar_panels_33.diode2.v",
    DP_[20],"solar_panels_33.diode2.R");
  W_[35] =  -DP_[22]*W_[28];
  helpvar[12] = W_[77]+X_[0];
  helpvar[13] = W_[71]+W_[33]+W_[35]+helpvar[12]-W_[24]-W_[31]-W_[63];
  W_[50] = W_[53]+W_[55]+W_[69]+helpvar[13]-W_[67]-W_[43];
  helpvar[14] = divmacro(W_[50],"solar_panels_32.signalcurrent2.n.v",DP_[29],
    "solar_panels_32.diode2.Vt");
  helpvar[15] = GreaterS(helpvar[14],"solar_panels_32.signalcurrent2.n.v/solar_panels_32.diode2.Vt",
     DP_[30],"solar_panels_32.diode2.Maxexp", 5);
  W_[51] = IF helpvar[15] THEN DP_[28]*(exp(DP_[30])*(1.0+helpvar[14]-DP_[30])-1)
    +divmacro(W_[50],"solar_panels_32.signalcurrent2.n.v",DP_[31],
    "solar_panels_32.diode2.R") ELSE DP_[28]*(exp(helpvar[14])-1)+divmacro(
    W_[50],"solar_panels_32.signalcurrent2.n.v",DP_[31],"solar_panels_32.diode2.R");
SetVector(residue__, 1, DP_[46]*W_[76]+W_[77]);
SetVector(residue__, 2, W_[68]-W_[60]+W_[27]);
SetVector(residue__, 3, W_[44]-W_[40]+W_[27]);
SetVector(residue__, 4, W_[51]-W_[40]+W_[27]);
SetVector(residue__, 5, W_[27]-W_[21]+W_[32]);
SetVector(residue__, 6, W_[32]-(W_[21]+W_[28]));

Jacobian(Jacobian__)
MatrixZeros(Jacobian__);
helpvar[16] = IF helpvar[9] THEN divmacro(DP_[13]*exp(DP_[15]),"solar_panels_33.diode1.Ids*exp(solar_panels_33.diode1.Maxexp)",
  DP_[14],"solar_panels_33.diode1.Vt")+divmacro(1.0,"1.0",DP_[16],
  "solar_panels_33.diode1.R") ELSE divmacro(DP_[13]*exp(helpvar[8]),
  "solar_panels_33.diode1.Ids*exp(solar_panels_33.diode1.v/solar_panels_33.diode1.Vt)",
  DP_[14],"solar_panels_33.diode1.Vt")+divmacro(1.0,"1.0",DP_[16],
  "solar_panels_33.diode1.R");
helpvar[17] = IF helpvar[7] THEN divmacro(DP_[35]*exp(DP_[37]),"solar_panels_31.diode1.Ids*exp(solar_panels_31.diode1.Maxexp)",
  DP_[36],"solar_panels_31.diode1.Vt")+divmacro(1.0,"1.0",DP_[38],
  "solar_panels_31.diode1.R") ELSE divmacro(DP_[35]*exp(helpvar[6]),
  "solar_panels_31.diode1.Ids*exp(solar_panels_31.diode1.v/solar_panels_31.diode1.Vt)",
  DP_[36],"solar_panels_31.diode1.Vt")+divmacro(1.0,"1.0",DP_[38],
  "solar_panels_31.diode1.R");
helpvar[18] = (-1.0)*helpvar[17];
helpvar[19] = IF helpvar[15] THEN divmacro(DP_[28]*exp(DP_[30]),"solar_panels_32.diode2.Ids*exp(solar_panels_32.diode2.Maxexp)",
  DP_[29],"solar_panels_32.diode2.Vt")+divmacro(1.0,"1.0",DP_[31],
  "solar_panels_32.diode2.R") ELSE divmacro(DP_[28]*exp(helpvar[14]),
  "solar_panels_32.diode2.Ids*exp(solar_panels_32.signalcurrent2.n.v/solar_panels_32.diode2.Vt)",
  DP_[29],"solar_panels_32.diode2.Vt")+divmacro(1.0,"1.0",DP_[31],
  "solar_panels_32.diode2.R");
helpvar[20] = (-1.0)*helpvar[19];
helpvar[21] = DP_[44]*helpvar[19]+DP_[43]*helpvar[19];
helpvar[22] = DP_[33]*helpvar[19];
helpvar[23] = IF helpvar[11] THEN divmacro(DP_[17]*exp(DP_[19]),"solar_panels_33.diode2.Ids*exp(solar_panels_33.diode2.Maxexp)",
  DP_[18],"solar_panels_33.diode2.Vt")+divmacro(1.0,"1.0",DP_[20],
  "solar_panels_33.diode2.R") ELSE divmacro(DP_[17]*exp(helpvar[10]),
  "solar_panels_33.diode2.Ids*exp(solar_panels_33.diode2.v/solar_panels_33.diode2.Vt)",
  DP_[18],"solar_panels_33.diode2.Vt")+divmacro(1.0,"1.0",DP_[20],
  "solar_panels_33.diode2.R");
SetMatrixLeading(Jacobian__, 1, 5, 6, DP_[46]*helpvar[16]);
SetMatrixLeading(Jacobian__, 1, 6, 6, DP_[46]+W_[5]);
SetMatrixLeading(Jacobian__, 2, 2, 6, IF helpvar[5] THEN divmacro(DP_[39]*exp(
  DP_[41]),"solar_panels_31.diode2.Ids*exp(solar_panels_31.diode2.Maxexp)",
  DP_[40],"solar_panels_31.diode2.Vt")+divmacro(1.0,"1.0",DP_[42],
  "solar_panels_31.diode2.R") ELSE divmacro(DP_[39]*exp(helpvar[4]),
  "solar_panels_31.diode2.Ids*exp(solar_panels_31.diode2.v/solar_panels_31.diode2.Vt)",
  DP_[40],"solar_panels_31.diode2.Vt")+divmacro(1.0,"1.0",DP_[42],
  "solar_panels_31.diode2.R"));
SetMatrixLeading(Jacobian__, 2, 3, 6, helpvar[18]);
SetMatrixLeading(Jacobian__, 3, 1, 6, IF helpvar[3] THEN divmacro(DP_[24]*exp(
  DP_[26]),"solar_panels_32.diode1.Ids*exp(solar_panels_32.diode1.Maxexp)",
  DP_[25],"solar_panels_32.diode1.Vt")+divmacro(1.0,"1.0",DP_[27],
  "solar_panels_32.diode1.R") ELSE divmacro(DP_[24]*exp(helpvar[2]),
  "solar_panels_32.diode1.Ids*exp(solar_panels_32.diode1.v/solar_panels_32.diode1.Vt)",
  DP_[25],"solar_panels_32.diode1.Vt")+divmacro(1.0,"1.0",DP_[27],
  "solar_panels_32.diode1.R"));
SetMatrixLeading(Jacobian__, 3, 3, 6, helpvar[18]);
SetMatrixLeading(Jacobian__, 4, 1, 6, helpvar[20]);
SetMatrixLeading(Jacobian__, 4, 2, 6, helpvar[20]);
SetMatrixLeading(Jacobian__, 4, 3, 6, ((-1.0)-(helpvar[21]+helpvar[22]+DP_[32]*
  helpvar[19]))*helpvar[17]-helpvar[19]);
SetMatrixLeading(Jacobian__, 4, 4, 6, helpvar[20]);
SetMatrixLeading(Jacobian__, 4, 5, 6, helpvar[20]-(DP_[21]*helpvar[19]+DP_[22]*
  helpvar[19])*helpvar[16]);
SetMatrixLeading(Jacobian__, 4, 6, 6, helpvar[19]*W_[5]);
SetMatrixLeading(Jacobian__, 5, 3, 6, helpvar[18]);
SetMatrixLeading(Jacobian__, 5, 4, 6, helpvar[23]);
SetMatrixLeading(Jacobian__, 6, 4, 6, helpvar[23]);
SetMatrixLeading(Jacobian__, 6, 5, 6, (-1.0)*helpvar[16]);

SolveNonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 1);
W_[43] = GetVector(x__, 1);
W_[67] = GetVector(x__, 2);
W_[63] = GetVector(x__, 3);
W_[31] = GetVector(x__, 4);
W_[24] = GetVector(x__, 5);
W_[3] = GetVector(x__, 6);
EndNonLinearSystemOfEquationsNH(residue__, x__, 1);
 /* End of Non-Linear Equation Block */ }



W_[70] = W_[27];
W_[48] =  -W_[27];
W_[54] = W_[27];
W_[34] =  -W_[28];
BreakSectionFunctionEnd()
BreakSectionFunctionStart(3);
W_[22] = W_[35]+W_[77]+X_[0];
W_[20] = W_[35]+W_[77]+X_[0]-W_[24];
W_[29] = W_[33]+W_[35]+W_[77]+X_[0]-W_[24];
W_[26] = W_[33]+W_[35]+W_[77]+X_[0]-W_[24]-W_[31];
W_[61] = W_[71]+W_[33]+W_[35]+W_[77]+X_[0]-W_[24]-W_[31];
W_[59] = W_[71]+W_[33]+W_[35]+W_[77]+X_[0]-W_[24]-W_[31]-W_[63];
W_[65] = W_[69]+W_[71]+W_[33]+W_[35]+W_[77]+X_[0]-W_[24]-W_[31]-W_[63];
W_[47] = W_[69]+W_[71]+W_[33]+W_[35]+W_[77]+X_[0]-W_[24]-W_[31]-W_[63]-W_[67];
W_[41] = W_[55]+W_[69]+W_[71]+W_[33]+W_[35]+W_[77]+X_[0]-W_[24]-W_[31]-W_[63]-
  W_[67];
W_[39] = W_[55]+W_[69]+W_[71]+W_[33]+W_[35]+W_[77]+X_[0]-W_[24]-W_[31]-W_[63]-
  W_[67]-W_[43];
 /* Linear system of equations to solve. */
F_[0] = RememberSimple_(F_[0], 6);
SolveScalarLinearParametric(DP_[47],"battcapsurrogate1.capacitor1.C",  -W_[76],
  " -battcapsurrogate1.pin_n.i", F_[0],"der(battcapsurrogate1.capacitor1.v)");
 /* End of Equation Block */ 


AcceptedSection1
beginwhenBlock
whenModelica(PRE(W_[19], 0) != 0 AND helpvar[1], 1) 
  W_[18] = PRE(W_[18], 1)-(IF PRE(W_[18], 1) > 0 THEN 1 ELSE 0);
endwhenModelica()
endwhenBlock

AcceptedSection2
W_[46] = W_[40]-W_[51];
W_[1] =  -(W_[76]+W_[46]);
W_[9] = W_[1]+W_[3];
W_[23] = W_[20]-W_[22];
W_[30] = W_[26]-W_[29];
W_[38] = W_[2]-W_[26];
W_[42] = W_[39]-W_[41];
W_[62] = W_[59]-W_[61];
W_[66] = W_[47]-W_[65];
W_[74] = W_[26]-W_[47];

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("varload1.pin_n.v", "Potential at the pin [V]", 0, 0.0,0.0,0.0,0,521)
DeclareVariable("varload1.pin_n.i", "Current flowing into the pin [A]", 0.0, \
0.0,0.0,0.0,0,776)
DeclareVariable("varload1.pin_p.v", "Potential at the pin [V]", 0.0, 0.0,0.0,0.0,\
0,520)
DeclareVariable("varload1.pin_p.i", "Current flowing into the pin [A]", 0.0, \
0.0,0.0,0.0,0,840)
DeclareAlias2("varload1.variableresistor1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 "varload1.pin_p.v", -1, 5, 2, 0)
DeclareAlias2("varload1.variableresistor1.i", "Current flowing from pin p to pin n [A]",\
 "varload1.pin_p.i", -1, 5, 3, 0)
DeclareVariable("varload1.variableresistor1.p.v", "Potential at the pin [V]", \
0.0, 0.0,0.0,0.0,0,521)
DeclareAlias2("varload1.variableresistor1.p.i", "Current flowing into the pin [A]",\
 "varload1.pin_p.i", -1, 5, 3, 132)
DeclareAlias2("varload1.variableresistor1.n.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("varload1.variableresistor1.n.i", "Current flowing into the pin [A]",\
 "varload1.pin_p.i", 1, 5, 3, 132)
DeclareVariable("varload1.variableresistor1.R", "[Ohm]", 0.0, 0.0,0.0,0.0,0,640)
DeclareParameter("varload1.pulse1.amplitude", "Amplitude of pulse [Ohm]", 0, 50,\
 0.0,0.0,0.0,0,560)
DeclareParameter("varload1.pulse1.width", "Width of pulse in % of periods", 1, 80,\
 1E-060,100.0,0.0,0,560)
DeclareParameter("varload1.pulse1.period", "Time for one period [s]", 2, 1, \
1E-060,1E+100,0.0,0,560)
DeclareParameter("varload1.pulse1.offset", "Offset of output signals [Ohm]", 3, 5,\
 0.0,0.0,0.0,0,560)
DeclareParameter("varload1.pulse1.startTime", "Output = offset for time < startTime [s]",\
 4, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("varload1.pulse1.y", "Connector of Real output signal [Ohm]", \
"varload1.variableresistor1.R", 1, 5, 5, 0)
DeclareVariable("varload1.pulse1.T0", "Start time of current period [s]", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("varload1.pulse1.T_width", "[s]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("varload1.ground1.p.v", "Potential at the pin [V]", 0.0, \
0.0,0.0,0.0,0,521)
DeclareVariable("varload1.ground1.p.i", "Current flowing into the pin [A]", 0.0,\
 0.0,0.0,0.0,0,776)
DeclareVariable("varload1.voltagesensor1.p.v", "Potential at the pin [V]", 0.0, \
0.0,0.0,0.0,0,521)
DeclareVariable("varload1.voltagesensor1.p.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("varload1.voltagesensor1.n.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareVariable("varload1.voltagesensor1.n.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("varload1.voltagesensor1.v", "Voltage between pin p and n (= p.v - n.v) as output signal [V]",\
 "varload1.pin_p.v", -1, 5, 2, 0)
DeclareAlias2("varload1.currentsensor1.p.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("varload1.currentsensor1.p.i", "Current flowing into the pin [A]",\
 "varload1.pin_p.i", -1, 5, 3, 132)
DeclareAlias2("varload1.currentsensor1.n.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("varload1.currentsensor1.n.i", "Current flowing into the pin [A]",\
 "varload1.pin_p.i", 1, 5, 3, 132)
DeclareAlias2("varload1.currentsensor1.i", "current in the branch from p to n as output signal [A]",\
 "varload1.pin_p.i", -1, 5, 3, 0)
DeclareAlias2("varload1.v", "[V]", "varload1.pin_p.v", -1, 5, 2, 0)
DeclareAlias2("varload1.i", "[A]", "varload1.pin_p.i", -1, 5, 3, 0)
DeclareVariable("samplesolarflux1.y", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("samplesolarflux1.trapezoid1.amplitude", "Amplitude of trapezoid",\
 5, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("samplesolarflux1.trapezoid1.rising", "Rising duration of trapezoid [s]",\
 6, 10, 0.0,1E+100,0.0,0,560)
DeclareParameter("samplesolarflux1.trapezoid1.width", "Width duration of trapezoid [s]",\
 7, 50, 0.0,1E+100,0.0,0,560)
DeclareParameter("samplesolarflux1.trapezoid1.falling", "Falling duration of trapezoid [s]",\
 8, 10, 0.0,1E+100,0.0,0,560)
DeclareParameter("samplesolarflux1.trapezoid1.period", "Time for one period [s]",\
 9, 500, 1E-060,1E+100,0.0,0,560)
DeclareParameter("samplesolarflux1.trapezoid1.nperiod", "Number of periods (< 0 means infinite number of periods) [:#(type=Integer)]",\
 10, -1, 0.0,0.0,0.0,0,564)
DeclareParameter("samplesolarflux1.trapezoid1.offset", "Offset of output signal",\
 11, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("samplesolarflux1.trapezoid1.startTime", "Output = offset for time < startTime [s]",\
 12, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("samplesolarflux1.trapezoid1.y", "Connector of Real output signal",\
 "samplesolarflux1.y", 1, 5, 13, 0)
DeclareVariable("samplesolarflux1.trapezoid1.T_rising", "End time of rising phase within one period [s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("samplesolarflux1.trapezoid1.T_width", "End time of width phase within one period [s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("samplesolarflux1.trapezoid1.T_falling", "End time of falling phase within one period [s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("samplesolarflux1.trapezoid1.T0", "Start time of current period [s]",\
 0.0, 0.0,0.0,0.0,0,2688)
DeclareVariable("samplesolarflux1.trapezoid1.counter", "Period counter [:#(type=Integer)]",\
 0, 0.0,0.0,0.0,0,2692)
DeclareVariable("samplesolarflux1.trapezoid1.counter2", "[:#(type=Integer)]", 0,\
 0.0,0.0,0.0,0,2692)
DeclareVariable("solar_panels_33.signalcurrent1.p.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("solar_panels_33.signalcurrent1.p.i", "Current flowing into the pin [A]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("solar_panels_33.signalcurrent1.n.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("solar_panels_33.signalcurrent1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_33.signalcurrent1.p.i", -1, 5, 21, 132)
DeclareVariable("solar_panels_33.signalcurrent1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_33.signalcurrent1.i", "Current flowing from pin p to pin n as input signal [A]",\
 "solar_panels_33.signalcurrent1.p.i", 1, 5, 21, 0)
DeclareVariable("solar_panels_33.diode1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,576)
DeclareVariable("solar_panels_33.diode1.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_33.diode1.p.v", "Potential at the pin [V]", \
"solar_panels_33.signalcurrent1.n.v", 1, 5, 22, 4)
DeclareAlias2("solar_panels_33.diode1.p.i", "Current flowing into the pin [A]", \
"solar_panels_33.diode1.i", 1, 5, 25, 132)
DeclareAlias2("solar_panels_33.diode1.n.v", "Potential at the pin [V]", \
"solar_panels_33.signalcurrent1.p.v", 1, 5, 20, 4)
DeclareAlias2("solar_panels_33.diode1.n.i", "Current flowing into the pin [A]", \
"solar_panels_33.diode1.i", -1, 5, 25, 132)
DeclareParameter("solar_panels_33.diode1.Ids", "Saturation current [A]", 13, \
1E-006, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_33.diode1.Vt", "Voltage equivalent of temperature (kT/qn) [V]",\
 14, 0.18, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_33.diode1.Maxexp", "Max. exponent for linear continuation [1]",\
 15, 15, 1E-060,1E+100,0.0,0,560)
DeclareParameter("solar_panels_33.diode1.R", "Parallel ohmic resistance [Ohm]", 16,\
 100000000.0, 0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_33.u", "", "samplesolarflux1.y", 1, 5, 13, 0)
DeclareVariable("solar_panels_33.pin_n.v", "Potential at the pin [V]", 0.0, \
0.0,0.0,0.0,0,520)
DeclareVariable("solar_panels_33.pin_n.i", "Current flowing into the pin [A]", \
0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("solar_panels_33.pin_p.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareVariable("solar_panels_33.pin_p.i", "Current flowing into the pin [A]", \
0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("solar_panels_33.signalcurrent2.p.v", "Potential at the pin [V]", \
"solar_panels_33.pin_n.v", 1, 5, 26, 4)
DeclareAlias2("solar_panels_33.signalcurrent2.p.i", "Current flowing into the pin [A]",\
 "solar_panels_33.signalcurrent1.p.i", 1, 5, 21, 132)
DeclareVariable("solar_panels_33.signalcurrent2.n.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("solar_panels_33.signalcurrent2.n.i", "Current flowing into the pin [A]",\
 "solar_panels_33.signalcurrent1.p.i", -1, 5, 21, 132)
DeclareVariable("solar_panels_33.signalcurrent2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_33.signalcurrent2.i", "Current flowing from pin p to pin n as input signal [A]",\
 "solar_panels_33.signalcurrent1.p.i", 1, 5, 21, 0)
DeclareVariable("solar_panels_33.diode2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,576)
DeclareVariable("solar_panels_33.diode2.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_33.diode2.p.v", "Potential at the pin [V]", \
"solar_panels_33.signalcurrent2.n.v", 1, 5, 29, 4)
DeclareAlias2("solar_panels_33.diode2.p.i", "Current flowing into the pin [A]", \
"solar_panels_33.diode2.i", 1, 5, 32, 132)
DeclareAlias2("solar_panels_33.diode2.n.v", "Potential at the pin [V]", \
"solar_panels_33.pin_n.v", 1, 5, 26, 4)
DeclareAlias2("solar_panels_33.diode2.n.i", "Current flowing into the pin [A]", \
"solar_panels_33.diode2.i", -1, 5, 32, 132)
DeclareParameter("solar_panels_33.diode2.Ids", "Saturation current [A]", 17, \
1E-006, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_33.diode2.Vt", "Voltage equivalent of temperature (kT/qn) [V]",\
 18, 0.18, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_33.diode2.Maxexp", "Max. exponent for linear continuation [1]",\
 19, 15, 1E-060,1E+100,0.0,0,560)
DeclareParameter("solar_panels_33.diode2.R", "Parallel ohmic resistance [Ohm]", 20,\
 100000000.0, 0.0,0.0,0.0,0,560)
DeclareVariable("solar_panels_33.resistor2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("solar_panels_33.resistor2.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_33.resistor2.p.v", "Potential at the pin [V]", \
"solar_panels_33.signalcurrent2.n.v", 1, 5, 29, 4)
DeclareAlias2("solar_panels_33.resistor2.p.i", "Current flowing into the pin [A]",\
 "solar_panels_33.resistor2.i", 1, 5, 34, 132)
DeclareAlias2("solar_panels_33.resistor2.n.v", "Potential at the pin [V]", \
"solar_panels_33.signalcurrent1.p.v", 1, 5, 20, 4)
DeclareAlias2("solar_panels_33.resistor2.n.i", "Current flowing into the pin [A]",\
 "solar_panels_33.resistor2.i", -1, 5, 34, 132)
DeclareParameter("solar_panels_33.resistor2.R", "Resistance [Ohm]", 21, 0.01, \
0.0,0.0,0.0,0,560)
DeclareVariable("solar_panels_33.resistor1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_33.resistor1.i", "Current flowing from pin p to pin n [A]",\
 "solar_panels_33.pin_p.i", -1, 5, 28, 0)
DeclareAlias2("solar_panels_33.resistor1.p.v", "Potential at the pin [V]", \
"solar_panels_33.signalcurrent1.n.v", 1, 5, 22, 4)
DeclareAlias2("solar_panels_33.resistor1.p.i", "Current flowing into the pin [A]",\
 "solar_panels_33.pin_p.i", -1, 5, 28, 132)
DeclareAlias2("solar_panels_33.resistor1.n.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("solar_panels_33.resistor1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_33.pin_p.i", 1, 5, 28, 132)
DeclareParameter("solar_panels_33.resistor1.R", "Resistance [Ohm]", 22, 0.01, \
0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_33.voltagesensor1.p.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareVariable("solar_panels_33.voltagesensor1.p.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("solar_panels_33.voltagesensor1.n.v", "Potential at the pin [V]", \
"solar_panels_33.pin_n.v", 1, 5, 26, 4)
DeclareVariable("solar_panels_33.voltagesensor1.n.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("solar_panels_33.voltagesensor1.v", "Voltage between pin p and n (= p.v - n.v) as output signal [V]",\
 "solar_panels_33.v", 1, 5, 38, 0)
DeclareAlias2("solar_panels_33.currentsensor1.p.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("solar_panels_33.currentsensor1.p.i", "Current flowing into the pin [A]",\
 "solar_panels_33.pin_p.i", -1, 5, 28, 132)
DeclareAlias2("solar_panels_33.currentsensor1.n.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("solar_panels_33.currentsensor1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_33.pin_p.i", 1, 5, 28, 132)
DeclareAlias2("solar_panels_33.currentsensor1.i", "current in the branch from p to n as output signal [A]",\
 "solar_panels_33.pin_p.i", -1, 5, 28, 0)
DeclareAlias2("solar_panels_33.i", "[A]", "solar_panels_33.pin_p.i", -1, 5, 28, 0)
DeclareVariable("solar_panels_33.v", "[V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("solar_panels_33.gain1.k", "Gain value multiplied with input signal",\
 23, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_33.gain1.u", "Input signal connector", \
"samplesolarflux1.y", 1, 5, 13, 0)
DeclareAlias2("solar_panels_33.gain1.y", "Output signal connector [A]", \
"solar_panels_33.signalcurrent1.p.i", 1, 5, 21, 0)
DeclareVariable("solar_panels_32.signalcurrent1.p.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("solar_panels_32.signalcurrent1.p.i", "Current flowing into the pin [A]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("solar_panels_32.signalcurrent1.n.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("solar_panels_32.signalcurrent1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_32.signalcurrent1.p.i", -1, 5, 40, 132)
DeclareVariable("solar_panels_32.signalcurrent1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_32.signalcurrent1.i", "Current flowing from pin p to pin n as input signal [A]",\
 "solar_panels_32.signalcurrent1.p.i", 1, 5, 40, 0)
DeclareVariable("solar_panels_32.diode1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,576)
DeclareVariable("solar_panels_32.diode1.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_32.diode1.p.v", "Potential at the pin [V]", \
"solar_panels_32.signalcurrent1.n.v", 1, 5, 41, 4)
DeclareAlias2("solar_panels_32.diode1.p.i", "Current flowing into the pin [A]", \
"solar_panels_32.diode1.i", 1, 5, 44, 132)
DeclareAlias2("solar_panels_32.diode1.n.v", "Potential at the pin [V]", \
"solar_panels_32.signalcurrent1.p.v", 1, 5, 39, 4)
DeclareAlias2("solar_panels_32.diode1.n.i", "Current flowing into the pin [A]", \
"solar_panels_32.diode1.i", -1, 5, 44, 132)
DeclareParameter("solar_panels_32.diode1.Ids", "Saturation current [A]", 24, \
1E-006, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_32.diode1.Vt", "Voltage equivalent of temperature (kT/qn) [V]",\
 25, 0.18, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_32.diode1.Maxexp", "Max. exponent for linear continuation [1]",\
 26, 15, 1E-060,1E+100,0.0,0,560)
DeclareParameter("solar_panels_32.diode1.R", "Parallel ohmic resistance [Ohm]", 27,\
 100000000.0, 0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_32.u", "", "samplesolarflux1.y", 1, 5, 13, 0)
DeclareVariable("solar_panels_32.pin_n.v", "Potential at the pin [V]", 0.0, \
0.0,0.0,0.0,0,521)
DeclareVariable("solar_panels_32.pin_n.i", "Current flowing into the pin [A]", \
0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("solar_panels_32.pin_p.v", "Potential at the pin [V]", 0.0, \
0.0,0.0,0.0,0,520)
DeclareVariable("solar_panels_32.pin_p.i", "Current flowing into the pin [A]", \
0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("solar_panels_32.signalcurrent2.p.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,521)
DeclareAlias2("solar_panels_32.signalcurrent2.p.i", "Current flowing into the pin [A]",\
 "solar_panels_32.signalcurrent1.p.i", 1, 5, 40, 132)
DeclareVariable("solar_panels_32.signalcurrent2.n.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("solar_panels_32.signalcurrent2.n.i", "Current flowing into the pin [A]",\
 "solar_panels_32.signalcurrent1.p.i", -1, 5, 40, 132)
DeclareAlias2("solar_panels_32.signalcurrent2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 "solar_panels_32.signalcurrent2.n.v", -1, 5, 50, 0)
DeclareAlias2("solar_panels_32.signalcurrent2.i", "Current flowing from pin p to pin n as input signal [A]",\
 "solar_panels_32.signalcurrent1.p.i", 1, 5, 40, 0)
DeclareAlias2("solar_panels_32.diode2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 "solar_panels_32.signalcurrent2.n.v", 1, 5, 50, 0)
DeclareVariable("solar_panels_32.diode2.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_32.diode2.p.v", "Potential at the pin [V]", \
"solar_panels_32.signalcurrent2.n.v", 1, 5, 50, 4)
DeclareAlias2("solar_panels_32.diode2.p.i", "Current flowing into the pin [A]", \
"solar_panels_32.diode2.i", 1, 5, 51, 132)
DeclareVariable("solar_panels_32.diode2.n.v", "Potential at the pin [V]", 0.0, \
0.0,0.0,0.0,0,521)
DeclareAlias2("solar_panels_32.diode2.n.i", "Current flowing into the pin [A]", \
"solar_panels_32.diode2.i", -1, 5, 51, 132)
DeclareParameter("solar_panels_32.diode2.Ids", "Saturation current [A]", 28, \
1E-006, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_32.diode2.Vt", "Voltage equivalent of temperature (kT/qn) [V]",\
 29, 0.18, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_32.diode2.Maxexp", "Max. exponent for linear continuation [1]",\
 30, 15, 1E-060,1E+100,0.0,0,560)
DeclareParameter("solar_panels_32.diode2.R", "Parallel ohmic resistance [Ohm]", 31,\
 100000000.0, 0.0,0.0,0.0,0,560)
DeclareVariable("solar_panels_32.resistor2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("solar_panels_32.resistor2.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_32.resistor2.p.v", "Potential at the pin [V]", \
"solar_panels_32.signalcurrent2.n.v", 1, 5, 50, 4)
DeclareAlias2("solar_panels_32.resistor2.p.i", "Current flowing into the pin [A]",\
 "solar_panels_32.resistor2.i", 1, 5, 54, 132)
DeclareAlias2("solar_panels_32.resistor2.n.v", "Potential at the pin [V]", \
"solar_panels_32.signalcurrent1.p.v", 1, 5, 39, 4)
DeclareAlias2("solar_panels_32.resistor2.n.i", "Current flowing into the pin [A]",\
 "solar_panels_32.resistor2.i", -1, 5, 54, 132)
DeclareParameter("solar_panels_32.resistor2.R", "Resistance [Ohm]", 32, 0.01, \
0.0,0.0,0.0,0,560)
DeclareVariable("solar_panels_32.resistor1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_32.resistor1.i", "Current flowing from pin p to pin n [A]",\
 "solar_panels_32.pin_p.i", -1, 5, 48, 0)
DeclareAlias2("solar_panels_32.resistor1.p.v", "Potential at the pin [V]", \
"solar_panels_32.signalcurrent1.n.v", 1, 5, 41, 4)
DeclareAlias2("solar_panels_32.resistor1.p.i", "Current flowing into the pin [A]",\
 "solar_panels_32.pin_p.i", -1, 5, 48, 132)
DeclareAlias2("solar_panels_32.resistor1.n.v", "Potential at the pin [V]", \
"solar_panels_32.pin_p.v", 1, 5, 47, 4)
DeclareAlias2("solar_panels_32.resistor1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_32.pin_p.i", 1, 5, 48, 132)
DeclareParameter("solar_panels_32.resistor1.R", "Resistance [Ohm]", 33, 0.01, \
0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_32.voltagesensor1.p.v", "Potential at the pin [V]", \
"solar_panels_32.pin_p.v", 1, 5, 47, 4)
DeclareVariable("solar_panels_32.voltagesensor1.p.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareVariable("solar_panels_32.voltagesensor1.n.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,521)
DeclareVariable("solar_panels_32.voltagesensor1.n.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("solar_panels_32.voltagesensor1.v", "Voltage between pin p and n (= p.v - n.v) as output signal [V]",\
 "solar_panels_32.pin_p.v", 1, 5, 47, 0)
DeclareAlias2("solar_panels_32.currentsensor1.p.v", "Potential at the pin [V]", \
"solar_panels_32.pin_p.v", 1, 5, 47, 4)
DeclareAlias2("solar_panels_32.currentsensor1.p.i", "Current flowing into the pin [A]",\
 "solar_panels_32.pin_p.i", -1, 5, 48, 132)
DeclareAlias2("solar_panels_32.currentsensor1.n.v", "Potential at the pin [V]", \
"solar_panels_32.pin_p.v", 1, 5, 47, 4)
DeclareAlias2("solar_panels_32.currentsensor1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_32.pin_p.i", 1, 5, 48, 132)
DeclareAlias2("solar_panels_32.currentsensor1.i", "current in the branch from p to n as output signal [A]",\
 "solar_panels_32.pin_p.i", -1, 5, 48, 0)
DeclareAlias2("solar_panels_32.i", "[A]", "solar_panels_32.pin_p.i", -1, 5, 48, 0)
DeclareAlias2("solar_panels_32.v", "[V]", "solar_panels_32.pin_p.v", 1, 5, 47, 0)
DeclareParameter("solar_panels_32.gain1.k", "Gain value multiplied with input signal",\
 34, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_32.gain1.u", "Input signal connector", \
"samplesolarflux1.y", 1, 5, 13, 0)
DeclareAlias2("solar_panels_32.gain1.y", "Output signal connector [A]", \
"solar_panels_32.signalcurrent1.p.i", 1, 5, 40, 0)
DeclareVariable("solar_panels_31.signalcurrent1.p.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("solar_panels_31.signalcurrent1.p.i", "Current flowing into the pin [A]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("solar_panels_31.signalcurrent1.n.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("solar_panels_31.signalcurrent1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_31.signalcurrent1.p.i", -1, 5, 60, 132)
DeclareVariable("solar_panels_31.signalcurrent1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_31.signalcurrent1.i", "Current flowing from pin p to pin n as input signal [A]",\
 "solar_panels_31.signalcurrent1.p.i", 1, 5, 60, 0)
DeclareVariable("solar_panels_31.diode1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,576)
DeclareVariable("solar_panels_31.diode1.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_31.diode1.p.v", "Potential at the pin [V]", \
"solar_panels_31.signalcurrent1.n.v", 1, 5, 61, 4)
DeclareAlias2("solar_panels_31.diode1.p.i", "Current flowing into the pin [A]", \
"solar_panels_31.diode1.i", 1, 5, 64, 132)
DeclareAlias2("solar_panels_31.diode1.n.v", "Potential at the pin [V]", \
"solar_panels_31.signalcurrent1.p.v", 1, 5, 59, 4)
DeclareAlias2("solar_panels_31.diode1.n.i", "Current flowing into the pin [A]", \
"solar_panels_31.diode1.i", -1, 5, 64, 132)
DeclareParameter("solar_panels_31.diode1.Ids", "Saturation current [A]", 35, \
1E-006, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_31.diode1.Vt", "Voltage equivalent of temperature (kT/qn) [V]",\
 36, 0.18, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_31.diode1.Maxexp", "Max. exponent for linear continuation [1]",\
 37, 15, 1E-060,1E+100,0.0,0,560)
DeclareParameter("solar_panels_31.diode1.R", "Parallel ohmic resistance [Ohm]", 38,\
 100000000.0, 0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_31.u", "", "samplesolarflux1.y", 1, 5, 13, 0)
DeclareAlias2("solar_panels_31.pin_n.v", "Potential at the pin [V]", \
"solar_panels_32.pin_p.v", 1, 5, 47, 4)
DeclareAlias2("solar_panels_31.pin_n.i", "Current flowing into the pin [A]", \
"solar_panels_32.pin_p.i", -1, 5, 48, 132)
DeclareAlias2("solar_panels_31.pin_p.v", "Potential at the pin [V]", \
"solar_panels_33.pin_n.v", 1, 5, 26, 4)
DeclareAlias2("solar_panels_31.pin_p.i", "Current flowing into the pin [A]", \
"solar_panels_33.pin_n.i", -1, 5, 27, 132)
DeclareAlias2("solar_panels_31.signalcurrent2.p.v", "Potential at the pin [V]", \
"solar_panels_32.pin_p.v", 1, 5, 47, 4)
DeclareAlias2("solar_panels_31.signalcurrent2.p.i", "Current flowing into the pin [A]",\
 "solar_panels_31.signalcurrent1.p.i", 1, 5, 60, 132)
DeclareVariable("solar_panels_31.signalcurrent2.n.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("solar_panels_31.signalcurrent2.n.i", "Current flowing into the pin [A]",\
 "solar_panels_31.signalcurrent1.p.i", -1, 5, 60, 132)
DeclareVariable("solar_panels_31.signalcurrent2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_31.signalcurrent2.i", "Current flowing from pin p to pin n as input signal [A]",\
 "solar_panels_31.signalcurrent1.p.i", 1, 5, 60, 0)
DeclareVariable("solar_panels_31.diode2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,576)
DeclareVariable("solar_panels_31.diode2.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_31.diode2.p.v", "Potential at the pin [V]", \
"solar_panels_31.signalcurrent2.n.v", 1, 5, 65, 4)
DeclareAlias2("solar_panels_31.diode2.p.i", "Current flowing into the pin [A]", \
"solar_panels_31.diode2.i", 1, 5, 68, 132)
DeclareAlias2("solar_panels_31.diode2.n.v", "Potential at the pin [V]", \
"solar_panels_32.pin_p.v", 1, 5, 47, 4)
DeclareAlias2("solar_panels_31.diode2.n.i", "Current flowing into the pin [A]", \
"solar_panels_31.diode2.i", -1, 5, 68, 132)
DeclareParameter("solar_panels_31.diode2.Ids", "Saturation current [A]", 39, \
1E-006, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_31.diode2.Vt", "Voltage equivalent of temperature (kT/qn) [V]",\
 40, 0.18, 0.0,0.0,0.0,0,560)
DeclareParameter("solar_panels_31.diode2.Maxexp", "Max. exponent for linear continuation [1]",\
 41, 15, 1E-060,1E+100,0.0,0,560)
DeclareParameter("solar_panels_31.diode2.R", "Parallel ohmic resistance [Ohm]", 42,\
 100000000.0, 0.0,0.0,0.0,0,560)
DeclareVariable("solar_panels_31.resistor2.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("solar_panels_31.resistor2.i", "Current flowing from pin p to pin n [A]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_31.resistor2.p.v", "Potential at the pin [V]", \
"solar_panels_31.signalcurrent2.n.v", 1, 5, 65, 4)
DeclareAlias2("solar_panels_31.resistor2.p.i", "Current flowing into the pin [A]",\
 "solar_panels_31.resistor2.i", 1, 5, 70, 132)
DeclareAlias2("solar_panels_31.resistor2.n.v", "Potential at the pin [V]", \
"solar_panels_31.signalcurrent1.p.v", 1, 5, 59, 4)
DeclareAlias2("solar_panels_31.resistor2.n.i", "Current flowing into the pin [A]",\
 "solar_panels_31.resistor2.i", -1, 5, 70, 132)
DeclareParameter("solar_panels_31.resistor2.R", "Resistance [Ohm]", 43, 0.01, \
0.0,0.0,0.0,0,560)
DeclareVariable("solar_panels_31.resistor1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("solar_panels_31.resistor1.i", "Current flowing from pin p to pin n [A]",\
 "solar_panels_33.pin_n.i", 1, 5, 27, 0)
DeclareAlias2("solar_panels_31.resistor1.p.v", "Potential at the pin [V]", \
"solar_panels_31.signalcurrent1.n.v", 1, 5, 61, 4)
DeclareAlias2("solar_panels_31.resistor1.p.i", "Current flowing into the pin [A]",\
 "solar_panels_33.pin_n.i", 1, 5, 27, 132)
DeclareAlias2("solar_panels_31.resistor1.n.v", "Potential at the pin [V]", \
"solar_panels_33.pin_n.v", 1, 5, 26, 4)
DeclareAlias2("solar_panels_31.resistor1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_33.pin_n.i", -1, 5, 27, 132)
DeclareParameter("solar_panels_31.resistor1.R", "Resistance [Ohm]", 44, 0.01, \
0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_31.voltagesensor1.p.v", "Potential at the pin [V]", \
"solar_panels_33.pin_n.v", 1, 5, 26, 4)
DeclareVariable("solar_panels_31.voltagesensor1.p.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("solar_panels_31.voltagesensor1.n.v", "Potential at the pin [V]", \
"solar_panels_32.pin_p.v", 1, 5, 47, 4)
DeclareVariable("solar_panels_31.voltagesensor1.n.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("solar_panels_31.voltagesensor1.v", "Voltage between pin p and n (= p.v - n.v) as output signal [V]",\
 "solar_panels_31.v", 1, 5, 74, 0)
DeclareAlias2("solar_panels_31.currentsensor1.p.v", "Potential at the pin [V]", \
"solar_panels_33.pin_n.v", 1, 5, 26, 4)
DeclareAlias2("solar_panels_31.currentsensor1.p.i", "Current flowing into the pin [A]",\
 "solar_panels_33.pin_n.i", 1, 5, 27, 132)
DeclareAlias2("solar_panels_31.currentsensor1.n.v", "Potential at the pin [V]", \
"solar_panels_33.pin_n.v", 1, 5, 26, 4)
DeclareAlias2("solar_panels_31.currentsensor1.n.i", "Current flowing into the pin [A]",\
 "solar_panels_33.pin_n.i", -1, 5, 27, 132)
DeclareAlias2("solar_panels_31.currentsensor1.i", "current in the branch from p to n as output signal [A]",\
 "solar_panels_33.pin_n.i", 1, 5, 27, 0)
DeclareAlias2("solar_panels_31.i", "[A]", "solar_panels_33.pin_n.i", 1, 5, 27, 0)
DeclareVariable("solar_panels_31.v", "[V]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("solar_panels_31.gain1.k", "Gain value multiplied with input signal",\
 45, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("solar_panels_31.gain1.u", "Input signal connector", \
"samplesolarflux1.y", 1, 5, 13, 0)
DeclareAlias2("solar_panels_31.gain1.y", "Output signal connector [A]", \
"solar_panels_31.signalcurrent1.p.i", 1, 5, 60, 0)
DeclareVariable("battcapsurrogate1.pin_n.v", "Potential at the pin [V]", 0.0, \
0.0,0.0,0.0,0,521)
DeclareVariable("battcapsurrogate1.pin_n.i", "Current flowing into the pin [A]",\
 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("battcapsurrogate1.pin_p.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("battcapsurrogate1.pin_p.i", "Current flowing into the pin [A]", \
"battcapsurrogate1.pin_n.i", -1, 5, 76, 132)
DeclareVariable("battcapsurrogate1.resistor1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("battcapsurrogate1.resistor1.i", "Current flowing from pin p to pin n [A]",\
 "battcapsurrogate1.pin_n.i", -1, 5, 76, 0)
DeclareAlias2("battcapsurrogate1.resistor1.p.v", "Potential at the pin [V]", \
"varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("battcapsurrogate1.resistor1.p.i", "Current flowing into the pin [A]",\
 "battcapsurrogate1.pin_n.i", -1, 5, 76, 132)
DeclareAlias2("battcapsurrogate1.resistor1.n.v", "Potential at the pin [V]", \
"battcapsurrogate1.capacitor1.v", 1, 1, 0, 4)
DeclareAlias2("battcapsurrogate1.resistor1.n.i", "Current flowing into the pin [A]",\
 "battcapsurrogate1.pin_n.i", 1, 5, 76, 132)
DeclareParameter("battcapsurrogate1.resistor1.R", "Resistance [Ohm]", 46, 0.05, \
0.0,0.0,0.0,0,560)
DeclareState("battcapsurrogate1.capacitor1.v", "Voltage drop between the two pins (= p.v - n.v) [V]",\
 0, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("battcapsurrogate1.capacitor1.der(v)", "der(Voltage drop between the two pins (= p.v - n.v)) [V/s]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("battcapsurrogate1.capacitor1.i", "Current flowing from pin p to pin n [A]",\
 "battcapsurrogate1.pin_n.i", -1, 5, 76, 0)
DeclareAlias2("battcapsurrogate1.capacitor1.p.v", "Potential at the pin [V]", \
"battcapsurrogate1.capacitor1.v", 1, 1, 0, 4)
DeclareAlias2("battcapsurrogate1.capacitor1.p.i", "Current flowing into the pin [A]",\
 "battcapsurrogate1.pin_n.i", -1, 5, 76, 132)
DeclareVariable("battcapsurrogate1.capacitor1.n.v", "Potential at the pin [V]", \
0.0, 0.0,0.0,0.0,0,521)
DeclareAlias2("battcapsurrogate1.capacitor1.n.i", "Current flowing into the pin [A]",\
 "battcapsurrogate1.pin_n.i", 1, 5, 76, 132)
DeclareParameter("battcapsurrogate1.capacitor1.C", "Capacitance [F]", 47, 100, \
0.0,1E+100,0.0,0,560)
DeclareAlias2("battcapsurrogate1.currentsensor1.p.v", "Potential at the pin [V]",\
 "varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("battcapsurrogate1.currentsensor1.p.i", "Current flowing into the pin [A]",\
 "battcapsurrogate1.pin_n.i", 1, 5, 76, 132)
DeclareAlias2("battcapsurrogate1.currentsensor1.n.v", "Potential at the pin [V]",\
 "varload1.pin_p.v", 1, 5, 2, 4)
DeclareAlias2("battcapsurrogate1.currentsensor1.n.i", "Current flowing into the pin [A]",\
 "battcapsurrogate1.pin_n.i", -1, 5, 76, 132)
DeclareAlias2("battcapsurrogate1.currentsensor1.i", "current in the branch from p to n as output signal [A]",\
 "battcapsurrogate1.pin_n.i", 1, 5, 76, 0)
DeclareAlias2("battcapsurrogate1.voltagesensor1.p.v", "Potential at the pin [V]",\
 "varload1.pin_p.v", 1, 5, 2, 4)
DeclareVariable("battcapsurrogate1.voltagesensor1.p.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareVariable("battcapsurrogate1.voltagesensor1.n.v", "Potential at the pin [V]",\
 0.0, 0.0,0.0,0.0,0,521)
DeclareVariable("battcapsurrogate1.voltagesensor1.n.i", "Current flowing into the pin [A]",\
 0, 0.0,0.0,0.0,0,777)
DeclareAlias2("battcapsurrogate1.voltagesensor1.v", "Voltage between pin p and n (= p.v - n.v) as output signal [V]",\
 "varload1.pin_p.v", 1, 5, 2, 0)
DeclareAlias2("battcapsurrogate1.i", "[A]", "battcapsurrogate1.pin_n.i", 1, 5, 76,\
 0)
DeclareAlias2("battcapsurrogate1.v", "[V]", "varload1.pin_p.v", 1, 5, 2, 0)
EndNonAlias(0)
#define NX_    1
#define NX2_   6
#define NU_    0
#define NY_    0
#define NW_    82
#define NP_    48
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1034790479
#define NHash2_ -486251386
#define NHash3_ 0
#define NI_    0
#define NRelF_ 6
#define NRel_  6
#define NTim_  6
#define NSamp_ 2
#define NCons_ 0
#define NA_    146
#define SizePre_ 2
#define SizeEq_ 7
#define SizeDelay_ 0
#define QNLmax_ 1
#define MAXAux 4
#define NrDymolaTimers_ 0
#define NWhen_ 2
#define NCheckIf_ 0
#define NGlobalHelp_ 24
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double *time, double X_[], double XD_[], double U_[], 
double DP_[], long IP_[], Dymola_bool LP_[], double F_[], double Y_[], double W_[], double QZ_[], double duser_[], long iuser_[], void*cuser_[]) {
static Real initStore[1];
}
StartDataBlock
StartPreBlock
preW(W_[18],"samplesolarflux1.trapezoid1.counter", DP_[10], 1);
pre(W_[19],"samplesolarflux1.trapezoid1.counter2", DP_[10], 0);
EndPreBlock
StartEqBlock
DoRemember_(F_[0], 0.0, 6);
DoRemember_(W_[63], 0.0, 2);
DoRemember_(W_[67], 0.0, 1);
DoRemember_(W_[43], 0.0, 0);
DoRemember_(W_[24], 0.0, 4);
DoRemember_(W_[31], 0.0, 3);
DoRemember_(W_[3], 0.0, 5);
EndEqBlock
UpdateQEvaluate(2)
UpdateSampleCounters(2)
EndDataBlock
BreakSectionFunctionStart(0);
BreakSectionFunctionCallNew(1);
BreakSectionFunctionCallNew(2);
BreakSectionFunctionCallNew(3);
BreakSectionFunctionEnd()
